name: CI

on:
  pull_request:
    branches:
      - main
      - develop
    push:
      branches:
        - main
        - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
          distribution: 'corretto'
          java-package: 'jdk'

      - name: Cache Gradle modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Check style
        run: ./gradlew checkstyle

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set PROJECT_NAME and PROJECT_VERSION from Gradle
        run: |
          echo "PROJECT_NAME=$(./gradlew properties | grep '^name:' | awk '{print $2}')" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$(./gradlew properties | grep '^version:' | awk '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}
          path: build/libs/${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.jar